Repository skyverge/kodiak-ui, pull requests merged in 2020-05, with the labels that each got.

#59 Create the Tooltip package in Kodiak UI
  .circleci/config.yml
  package.json
  packages/hooks/src/index.ts
  packages/hooks/src/useId.ts
  packages/storybook/package.json
  packages/storybook/src/Tooltip/Tooltip.stories.tsx
  packages/storybook/src/theme.ts
  packages/tooltip/package.json
  packages/tooltip/src/Tooltip.tsx
  packages/tooltip/src/TooltipArrow.tsx
  packages/tooltip/src/__tests__/Tooltip.spec.tsx
  packages/tooltip/src/__tests__/TooltipArrow.spec.tsx
  packages/tooltip/src/__tests__/useTooltip.spec.tsx
  packages/tooltip/src/index.ts
  packages/tooltip/src/useTooltip.ts
  packages/tooltip/tsconfig.json
  yarn.lock
Labels: components, hooks

#62 Update kodiak-ui/select with a loading indicator
  packages/primitives/src/Loading/DotLoadingIndicator.tsx
  packages/primitives/src/Loading/__tests__/DotLoadingIndicator.spec.tsx
  packages/primitives/src/Loading/index.ts
  packages/primitives/src/index.ts
  packages/storybook/src/Select/Select.stories.tsx
  packages/storybook/src/primitives/Loading/Loading.stories.tsx
  packages/table/src/TableHeader.tsx
  packages/table/src/utils.ts
Labels: components

#65 Remove outline on menu and add pointer to item
  packages/menu/src/MenuList.tsx
  packages/menu/src/MenuListItem.tsx
Labels: components

#66 Allow useAccordion to be controlled
  packages/accordion/src/useAccordion.ts
  packages/storybook/src/Accordion/Accordion.stories.tsx
Labels: hooks

#67 Create horizontal tab Navigation variant in kodiak
  packages/primitives/src/Menu/index.ts
  packages/primitives/src/Nav/Nav.tsx
  packages/primitives/src/Nav/NavItem.tsx
  packages/primitives/src/Nav/__tests__/Nav.spec.tsxh
  packages/primitives/src/Nav/index.ts
  packages/primitives/src/index.ts
  packages/storybook/src/primitives/Nav/Nav.stories.tsx
  packages/storybook/src/theme.ts
Labels: components

#69 Implement Avatar component in kodiak-ui that can accept an image or text
  packages/primitives/src/Image/Image.tsx
  packages/primitives/src/Image/__tests__/Image.spec.tsx
  packages/primitives/src/Image/index.ts
  packages/primitives/src/index.ts
  packages/storybook/src/primitives/Avatar/Avatar.stories.tsx
  packages/storybook/src/primitives/Avatar/image.jpg
  packages/storybook/src/primitives/Image/Image.stories.tsx
  packages/storybook/src/primitives/Image/image.jpg
  packages/storybook/src/theme.ts
Labels: components
